version: 2
jobs:
  build:
    # ...
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install requests
            sudo pip install jsonpath
            sudo python wangzhingting.py
            sudo ./index